# fly.toml app configuration file generated for belugalaundry-cms on 2024-07-29T17:49:51+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'belugalaundry-cms'
primary_region = 'syd'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
